[package]
name = "subsign-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tokio-macros = { version = "2.4.0" }
serde = { version = "1.0.228", features = ["derive"] }
config-file = "0.2.3"
